-- Pitch-level Statcast cache schema.
-- Created automatically on first run when the local database is empty.

CREATE TABLE IF NOT EXISTS "pitches" (
"pitch_type" TEXT,
  "game_date" TEXT,
  "release_speed" REAL,
  "release_pos_x" REAL,
  "release_pos_z" REAL,
  "player_name" TEXT,
  "batter" INTEGER,
  "pitcher" INTEGER,
  "events" TEXT,
  "description" TEXT,
  "spin_dir" REAL,
  "spin_rate_deprecated" REAL,
  "break_angle_deprecated" REAL,
  "break_length_deprecated" REAL,
  "zone" REAL,
  "des" TEXT,
  "game_type" TEXT,
  "stand" TEXT,
  "p_throws" TEXT,
  "home_team" TEXT,
  "away_team" TEXT,
  "type" TEXT,
  "hit_location" REAL,
  "bb_type" TEXT,
  "balls" INTEGER,
  "strikes" INTEGER,
  "game_year" INTEGER,
  "pfx_x" REAL,
  "pfx_z" REAL,
  "plate_x" REAL,
  "plate_z" REAL,
  "on_3b" REAL,
  "on_2b" REAL,
  "on_1b" REAL,
  "outs_when_up" INTEGER,
  "inning" INTEGER,
  "inning_topbot" TEXT,
  "hc_x" REAL,
  "hc_y" REAL,
  "tfs_deprecated" REAL,
  "tfs_zulu_deprecated" REAL,
  "umpire" REAL,
  "sv_id" REAL,
  "vx0" REAL,
  "vy0" REAL,
  "vz0" REAL,
  "ax" REAL,
  "ay" REAL,
  "az" REAL,
  "sz_top" REAL,
  "sz_bot" REAL,
  "hit_distance_sc" REAL,
  "launch_speed" REAL,
  "launch_angle" REAL,
  "effective_speed" REAL,
  "release_spin_rate" REAL,
  "release_extension" REAL,
  "game_pk" INTEGER,
  "fielder_2" INTEGER,
  "fielder_3" INTEGER,
  "fielder_4" INTEGER,
  "fielder_5" INTEGER,
  "fielder_6" INTEGER,
  "fielder_7" INTEGER,
  "fielder_8" INTEGER,
  "fielder_9" INTEGER,
  "release_pos_y" REAL,
  "estimated_ba_using_speedangle" REAL,
  "estimated_woba_using_speedangle" REAL,
  "woba_value" REAL,
  "woba_denom" REAL,
  "babip_value" REAL,
  "iso_value" REAL,
  "launch_speed_angle" REAL,
  "at_bat_number" INTEGER,
  "pitch_number" INTEGER,
  "pitch_name" TEXT,
  "home_score" INTEGER,
  "away_score" INTEGER,
  "bat_score" INTEGER,
  "fld_score" INTEGER,
  "post_away_score" INTEGER,
  "post_home_score" INTEGER,
  "post_bat_score" INTEGER,
  "post_fld_score" INTEGER,
  "if_fielding_alignment" TEXT,
  "of_fielding_alignment" TEXT,
  "spin_axis" REAL,
  "delta_home_win_exp" REAL,
  "delta_run_exp" REAL,
  "bat_speed" REAL,
  "swing_length" REAL,
  "miss_distance" REAL,
  "estimated_slg_using_speedangle" REAL,
  "delta_pitcher_run_exp" REAL,
  "hyper_speed" REAL,
  "home_score_diff" INTEGER,
  "bat_score_diff" INTEGER,
  "home_win_exp" REAL,
  "bat_win_exp" REAL,
  "age_pit_legacy" INTEGER,
  "age_bat_legacy" INTEGER,
  "age_pit" INTEGER,
  "age_bat" INTEGER,
  "n_thruorder_pitcher" INTEGER,
  "n_priorpa_thisgame_player_at_bat" INTEGER,
  "pitcher_days_since_prev_game" REAL,
  "batter_days_since_prev_game" REAL,
  "pitcher_days_until_next_game" REAL,
  "batter_days_until_next_game" REAL,
  "api_break_z_with_gravity" REAL,
  "api_break_x_arm" REAL,
  "api_break_x_batter_in" REAL,
  "arm_angle" REAL,
  "attack_angle" REAL,
  "attack_direction" REAL,
  "swing_path_tilt" REAL,
  "intercept_ball_minus_batter_pos_x_inches" REAL,
  "intercept_ball_minus_batter_pos_y_inches" REAL,
  "season" INTEGER
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pitch_identity
ON pitches (pitcher, game_pk, at_bat_number, pitch_number)
WHERE pitcher IS NOT NULL
  AND game_pk IS NOT NULL
  AND at_bat_number IS NOT NULL
  AND pitch_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS official_outings (
  game_pk INTEGER NOT NULL,
  pitcher_id INTEGER NOT NULL,
  game_date TEXT NOT NULL,
  season INTEGER,
  team TEXT,
  opponent TEXT,
  home_away TEXT,
  innings_pitched TEXT,
  outs_recorded INTEGER,
  hits INTEGER,
  runs INTEGER,
  earned_runs INTEGER,
  walks INTEGER,
  intentional_walks INTEGER,
  hit_by_pitch INTEGER,
  strikeouts INTEGER,
  home_runs INTEGER,
  batters_faced INTEGER,
  pitches INTEGER,
  strikes INTEGER,
  balls INTEGER,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (game_pk, pitcher_id)
);

CREATE INDEX IF NOT EXISTS idx_official_outings_pitcher_date
ON official_outings (pitcher_id, game_date);

CREATE TABLE IF NOT EXISTS schema_version (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
);
